fix: Raise the underlying urlerror while downloading example file (#4396)
While downloading the example file, if there is an
`urllib.error.URLError` due to an `SSLError`, raise the underlying
`SSLError`. For all other cases raise `RemoteFileNotFoundError` as
before.

Example SSLError:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

Showing the underlying error will help users to triage connection issues
in their system, e.g. the above error is due to CA certificates are not
installed on the system.

Fluent bug - 1320755

---------

Co-authored-by: pyansys-ci-bot <92810346+pyansys-ci-bot@users.noreply.github.com>